# Generated by Django 4.0.2 on 2022-02-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(default='', max_length=10),
        ),
    ]
