# Generated by Django 4.0.2 on 2022-02-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_password1_profile_password2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
