# Generated by Django 3.2.7 on 2022-03-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220325_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verify',
        ),
    ]
