# Generated by Django 3.2.7 on 2022-03-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_company', models.CharField(max_length=200)),
                ('lead_name', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=10)),
                ('lead_email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('requirement', models.CharField(max_length=1500)),
                ('lead_managed', models.CharField(max_length=200)),
            ],
        ),
    ]
