# Generated by Django 4.0.2 on 2022-03-12 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='leads',
            name='last_contacted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
