# Generated by Django 4.0.2 on 2022-03-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_leads_create_date_leads_last_contacted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
