# Generated by Django 3.2.7 on 2022-03-15 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_company', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=10)),
                ('lead_email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('requirement', models.CharField(max_length=1500)),
                ('lead_managed', models.CharField(max_length=200)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('last_contacted', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
