# Generated by Django 4.0.2 on 2022-03-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
