# Generated by Django 4.0.2 on 2022-03-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_task_managed_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
