# Generated by Django 3.2.7 on 2022-03-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_leads_user_name'),
        ('sales', '0012_task'),
    ]

    operations = [
    ]
