# Generated by Django 2.2 on 2022-04-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_customer_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        
    ]
