# Generated by Django 2.2 on 2022-04-23 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0015_auto_20220423_1515'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('member1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='member1', to=settings.AUTH_USER_MODEL)),
                ('member2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='member2', to=settings.AUTH_USER_MODEL)),
                ('team_manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
